---
title: "Case 31 Assignment: Data Preparation"
author: "Jae Jung"
format: 
  html:
    toc: true
    toc-depth: 2
    embed-resources: true
editor: visual
---

# Loading libraries

```{r}
# install.packages("haven")
library(tidyverse)
library(haven) # for importing spss or labelled data
library(labelled) # for working with labelled data
library(janitor) 
library(sjPlot)
```

# Import Data

```{r}
data <- read_spss("Case 31 Data_efcu_1.sav")
data <- data |> 
  clean_names()

data_dictionary <- data |>
  view_df()

data_dictionary
```

# Recoding

```{r}
data |> 
  count(q3) |> 
  mutate(percent = n/sum(n))

data <- data |> 
  set_value_labels(q3 = c("Strongly Disagree" = 1,
                          "Disagree" = 2,
                          "Uncertain" = 3,
                          "Agree" = 4,
                          "Strongly Agree" = 5))

data |> 
  select(q3) |> 
  var_label() 

data |> 
  select(q3) |> 
  val_labels()



```

# Multi-item measures

## Reliability analysis

```{r}

```

## Creating a composite scale

```{r}

```
