---
title: "Project with Case 31"
subtitle: "Data Preparation"
author: "Jae Jung"
institute: "IBM 3302, Cal Poly Pomona"
date: "`r Sys.Date()`"
format: 
  revealjs:
    footer: Case 31 Project
    transition: slide
    transition-speed: default
    toc: true
    toc-depth: 1
    slide-number: true
    scrollable: true
    smaller: true
    code-fold: false
    code-overflow: wrap
    code-copy: true
    number-sections: true
    embed-resources: true
    self-contained-math: true
editor: visual
execute: 
  echo: true
  freeze: auto
---

# Libraries {background-color="aquamarine"}

## Loading common packages

```{r}
# install.packages("haven")
library(tidyverse)
library(haven) 
library(labelled) 
library(janitor) 
library(sjPlot)
library(psych)
set_theme(theme_minimal())
```

# Setting Up Data {background-color="aquamarine"}

## Reading SPSS data {.smaller}

```{r}
#| output-location: fragment

data <- read_spss("Case 31 Data_efcu_1.sav")
data <- data |> 
  clean_names()

# generate data dictionary
data |>
  view_df()

```

# Data Preparation {background-color="aquamarine"}

## Attitudes towards Employee Proficiency {.smaller}

### q3

```{r}
data |> # ctr + shift + M
  count(q3) |> 
  mutate(percent = n/sum(n))
```

------------------------------------------------------------------------

```{r}
data_clean <- data |> 
  set_value_labels(q3 = c("Strongly Disagree" = 1,
                          "Disagree" = 2,
                          "Uncertain" = 3,
                          "Agree" = 4,
                          "Strongly Agree" = 5)) |> 
  set_variable_labels(q3 = "Employees are Courteous")

data_clean |> 
  select(q3) |> 
  var_label() 

data_clean |> 
  select(q3) |> 
  val_labels()
```

------------------------------------------------------------------------

### q4 {.smaller}

```{r}
data_clean <-  data_clean |> 
  set_variable_labels(q4 = "Employees are helpful") |> 
  set_value_labels(q4 = c("Strongly Disagree" = 1,
                          "Disagree" = 2,
                          "Uncertain" = 3,
                          "Agree" = 4,
                          "Strongly Agree" = 5)) 

data_clean |> 
  select(q4) |>
  var_label()

data_clean |> 
  select(q4) |> 
  val_labels()
```

------------------------------------------------------------------------

### q5 and q6

```{r}
data_clean <- data_clean |> 
  set_variable_labels(q5 = "Employees are professional") |> 
  set_value_labels(q5 = c("Strongly Disagree" = 1,
                          "Disagree" = 2,
                          "Uncertain" = 3,
                          "Agree" = 4,
                          "Strongly Agree" = 5)) |> 
  set_variable_labels(q6 = "Employees are available") |> 
  set_value_labels(q6 = c("Strongly Disagree" = 1,
                          "Disagree" = 2,
                          "Uncertain" = 3,
                          "Agree" = 4,
                          "Strongly Agree" = 5))
data_clean |> 
  select(q5, q6) |>
  var_label()

data_clean |> 
  select(q5, q6) |> 
  val_labels()
```

------------------------------------------------------------------------
> 11/25/2024

